---
title: "Create a Website"
---
## Intoduction

In the previous chapters, we discussed that creating an online book to host the materials would be a way to make the resources more machine-actionable and generally more findable.
There are many examples of scholars, organizations, and individuals who have shared their materials using a website created with Quarto.
Here is a list of just a few of them, utilizing different features of Quarto for educational purposes:

| Creator(s)                                           	| Topic                                                                                                                     	| URL                                               	|
|------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------	|
| Lennart Wittkuhn, Konrad Pagenstedt & Liese Kümmerle 	| An extensive and comprehensive guide to GitHub, which was primarily taught in a seminar format at the University of Hamburg. 	| [Version Control Book](https://lennartwittkuhn.com/version-control-book/) 	|
| Mine Çetinkaya-Rundel                                	| Advanced data visualization course taught at Duke University                                                              	| [Advanced Data Visualization](http://vizdata.org/)                               	|
| Andrew Heiss                                         	| Data visualization with R                                                                                                 	| [Data Visualization with R](https://datavizf24.classes.andrewheiss.com/)       	|
| The psyTeachR team at the University of Glasgow      	| Teaching reproducible research skills                                                                                     	| [Data Skills for Reproducible Research](https://psyteachr.github.io/reprores-v4/)          	|


## Quarto for educational websites
You have probably realized that Quarto is a great tool for creating reproducible documents.
However, it is not primarily a tool for website development.
That being said, it has the power to create a couple of specific types of websites that align with the main goal of Quarto—namely, reproducibility.

If you have tried to create a website before, you probably know that getting started is not easy.
Maybe you've used online website generators or even gone beyond that to learn HTML or WordPress.
Unlike these tools, which are specifically developed for website creation, Quarto serves a different purpose—so why use Quarto instead?

First of all, the FAIR principles can also be applied to websites created with Quarto.
Second, it is much easier to create a website using Quarto.
There are built-in templates and extensive customization options that cover almost everything a standard educational website needs.

The biggest advantage of using Quarto to create a website appears when you have already used it to host your materials in Quarto's other formats i.e. manuscripts and slides.
For example, you've created slides, written lecture notes, and embedded multimedia resources using Quarto.
Now, you want to make everything publicly available.
With just a few clicks and some modifications to the `yml` file, you can see the magic of Quarto in bringing everything together.

Lastly, creating and maintaining a website with Quarto can be completely free when combined with GitHub.
This further highlights how powerful these tools can be when used together.

You can watch this video from Brian Tarran's presentation on Posit conference about his journey of website making using Quarto.


<iframe width="560" height="315" src="https://www.youtube.com/embed/ncDEqHxMWnE?si=yp71b-NEs5a4QmxG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


## Basics of creating a website

### Create a Quarto Website

First, we have to create a Quarto project in RStudio for our website and locate its directory.
(Image from a project)

For version control purposes, check Create a Git repository.
Leave the other options intact if you don't need them in your workflow.
Click on Create Project.

You can see the files that RStudio has created for you under the Files tab.
For now, we mainly work with `.qmd` and `.yml` files.
The `index.qmd` file is your homepage.
You can render it to see a quick preview of how the website looks.

### Locating the Website Folder

When hosting a website, GitHub needs to know where the project files are stored in order to load and render them properly.

Initially, the `_site` folder in the website project stores the website files.
However, to connect our website to GitHub, we need to change the output directory of the website files to another folder called `docs`.

To do this, open your `yml` file.
Below `type: website`, add the following line:
`output-dir: docs`

Be careful when modifying the `yml` file, as it is highly sensitive to hierarchy and will throw errors if not configured correctly.

Now, your `yml` file should look like this:

```
project:
  type: website
  output-dir: docs

```
Feel free to delete the `_site` folder.


### Connect the website to GitHub

Assuming you have a GitHub account, you can connect your local Quarto project to GitHub, hosted by GitHub Pages.
Your website address will be: `yourgithubusername.github.io`, so choose your GitHub username wisely.

Go to your GitHub account and create a new repository for your website—we’ll call it `yourrepository`.
(Image)
Leave the other options intact and click on **Create Repository**.

In your Quarto website project, navigate to the **Terminal** tab (located near **Console**) and tell RStudio where to push your website using the following commands:

```
git remote add origin https://github.com/username/yourrepository  
git branch -M main
git add --all
git commit -m "initial commit"
git push -u origin main

```

1. Tell RStudio where the corresponding GitHub repository is to then push the files into it.
2. Creates a GitHub brach called `main`.
3. Stages all the changed files.
4. Commits the changes.
5. Finally, pushes the changed files into the GitHub repo.

This can also be done in Git Bash or other terminals.

Now, if you refresh your repository on GitHub, you'll see that the files have been pushed.

In the repository, click **Settings**, then navigate to Pages on the left side.
Here, you need to specify your `main` branch and set the `docs` folder as the location where changes and files are committed and stored.

Congratulations!
Your website is now live at `yourgithubusername.github.io`.

### Adding Pages to Your Website
Every `.qmd` file created in your project can be a page on your website.
We recommend storing all the pages in a specific folder to keep your project organized.
Under the **Files** tab, click on the icon to create a new document and choose **Quarto Document**.

For example, if you want to have a page on the website that introduces the course you are teaching,
create a `.qmd` file called `introduction` in the pages folder we created earlier.
Then, navigate to the `_yml` file.
Here, we need to add the `introduction` page.

```
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - pages\introduction.qmd
```
By rendering the `index.qmd` file, we'll see that `introduction.qmd` has been added to the website.
You can add content to the file as discussed in the previous chapters.

You may have noticed that we've added - `pages\introduction.qmd`, a relative path, to specify where the introduction.qmd file is located.
It is called a relative path because it is relative to our `index.qmd` file.
The way you reference files is very important in Quarto, so double-check everything when writing relative paths.

There are also absolute paths, in which you specify exactly where the file is located on your computer.
Relative paths are more advantageous because they can be executed on other systems seamlessly.



### More Beautiful Websites
Quarto supports CSS customization, so if you are familiar with it—kudos!
But if you are not very familiar with web development tools, don't worry.

Quarto has [25 built-in themes](https://quarto.org/docs/websites/website-blog.html#themes).
As usual, we refer to the `_yml` file to manipulate the theming of our website.
In the lower part of the default `_yml` file, you can find the `html` formatting, where we apply the customization.

```
format:
  html:
    theme: cosmo
```
By default, Quarto uses the cosmo theme.
You can replace it with either of the 25 themes, for example:

```
format:
  html:
    theme: lux
```
That’s all you need to create a fully functional website with a touch of customization to make your work publicly available using Quarto.
Quarto offers a ton of customization features and modification options for websites, which you can access [here](https://quarto.org/docs/websites/).

We believe that making it easier to start a FAIR project is more important than creating a perfect website.
Alongside your project, you can learn how to customize it further and add more features, but the core skills needed to start the project are discussed here.