---
title: "The FAIR Framework"
abstract: |
  What are FAIR principles?
  How can open educational resources be FAIR?
---

# The FAIR Framework 

Since science has transitioned from pens and paper to keyboards and monitors, developing an appropriate approach to archiving, reproducing, sharing, and collaborating on scientific outputs seems inevitable.
One of the most well-known frameworks developed by @wilkinson2016 to define best practices in research data management are the **FAIR** principles. FAIR stands for ***Findable***, ***Accessible***, ***Interoperable***, and ***Reusable***.
The FAIR principles serve as a guide to achieving better data management.
They enable data to be ***machine actionable***, meaning they equip autonomous computational systems with detailed, structured information while analyzing and processing the data.

## What is Findable, Accessible, Interoperable, and Reusable? {.unnumbered}

According to the FAIR principles:

-   data are **Findable**,

    -   when they are indexed in a searchable resource,
    -   described with excessive metadata,
    -   have a unique identifier such as a DOI,
    -   include the identifier in the metadata.

-   **Accessible data**,

    -   can be accessed through their identifier,
    -   has a free, universally accessible, and open protocol,
    -   supports authentication processes when required
    -   have an accessible metadata regardless of the data availability.

-   **Interoperable** data and metadata,

    -   present knowledge in a standard language.
    -   adapt with FAIR terminology.
    -   contain references to other data or metadata .

-   **Reusable** means,

    -   data and metadata are attributed accurately.
    -   data and metadata have suitable data usage licenses.
    -   data and metadata are connected thoroughly.
    -   data and metadata meet the standards of the respective scientific community.

Since the FAIR values are principles that guide researchers along their scientific journey, we directly quote @wilkinson2016's definition of every principle to leave no room for interpretation:

::: {.callout-tip collapse=true}
## To be Findable:

**F1.** (meta)data are assigned a globally unique and persistent identifier.

**F2.** data are described with rich metadata (defined by R1 below).

**F3.** metadata clearly and explicitly include the identifier of the data it describes.

**F4.** (meta)data are registered or indexed in a searchable resource.
:::

::: {.callout-tip collapse="true"}
## To be Accessible:

**A1.** (meta)data are retrievable by their identifier using a standardized communications protocol.

**A1.1.** the protocol is open, free, and universally implementable.

**A1.2.** the protocol allows for an authentication and authorization procedure, where necessary.

**A2.** metadata are accessible, even when the data are no longer available.
:::

::: {.callout-tip collapse="true"}
## To be Interoperable:

**I1.** (meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation.

**I2.** (meta)data use vocabularies that follow FAIR principles.

**I3.** (meta)data include qualified references to other (meta)data
:::

::: {.callout-tip collapse="true"}
## To be Reusable

**R1.** meta(data) are richly described with a plurality of accurate and relevant attributes.

**R1.1.** (meta)data are released with a clear and accessible data usage license.

**R1.2.** (meta)data are associated with detailed provenance.

**R1.3.** (meta)data meet domain-relevant community standards
:::

# FAIR Principles for Educational Resources {.unnumbered}

With most of the focus being on the FAIRness of the data, not enough attention is paid to the materials that actually educate future researchers.
Throughout this guide, we argue that not only can research data be FAIR, but the same principles are also applicable to teaching materials.
By using a suitable framework, the educational content produced in numerous institutions around the globe can become FAIR and even exceed these values.
@garcia2020 introduced 10 rules for developing more accessible training materials.

## Rule 1: Sharing the Materials Online {.unnumbered}

This has several benefits, for example, online materials can gain recognition and assist other researchers in the field.
It is also helpful to the students as they can access the materials regardless of their location.
Building a dedicated website is also a desirable way to share the teaching materials online.
In this way, contributing to the content becomes easier.
A website also provides options to make materials interactive. For example, quizzes or exams after each chapter can create opportunities for both the instructor and the student to assess the materials and the knowledge gained.
This approach has been taken in the [Version Control Book](https://lennartwittkuhn.com/version-control-book) by [Lennart Wittkuhn](https://lennartwittkuhn.com) and Konrad Pagenstedt.
[Data Science in a Box](https://datasciencebox.org/) by [Mine Çetinkaya-Rundel](https://mine-cr.com/) and [R for Psych](https://glennwilliams.me/r4psych/) by [Glenn Williams](https://glennwilliams.me/) are also notable examples that share their materials online on a website.

::: {.callout-caution collapse="true"}
## How are your materials shared with others? {.unnumbered}
- [ ] I have shared my materials on a dedicated website.
- [ ] I have shared my materials on a cloud service (e.g., {{< fa brands google-drive >}} Google Drive, {{< fa brands dropbox >}} Dropbox, {{< fa solid cloud >}} iCloud)
- [ ] My README file describes the necessary steps to reproduce the materials in the respective folder.
:::

## Rule 2: Proper Description for Findability {.unnumbered}

Writing extensive metadata for the materials helps with their findability by making them more machine actionable.
For example, working with a dataset from another researcher in which all the variables and their labels are properly described is much easier and less time-consuming than another dataset without such description.
The same applies to teaching materials designed for interaction with computers.
Appropriate document description is also useful when students want to interact with the materials.
It acts as a guide through the materials and prevents confusion for the audience.

::: {.callout-caution collapse="true"}
## How are your materials described? {.unnumbered}
- [ ] I have a README file for the project.
- [ ] I have README files for each top level sub-folder.
- [ ] My README file describes the necessary steps to reproduce the materials in the respective folder.
:::

## Rule 3: Unique Identity for the Materials {.unnumbered}
You have probably encountered a situation where clicking on a link in a research paper does not navigate you to the intended web destination.
One possible explanation for such an issue could be *link rot*.
Link rot means that links no longer work due to the relocation or permanent unavailability of a webpage, file, or whatever they are pointing to.
This happens because the links don't possess persistent identifiers (PIDs) such as a Digital Object Identifier (DOI).
PIDs guarantee that the link won't become invalid and will always be accessible.
Services like Open Researcher and Contributor ID (ORCID) and Zenodo (see the chapter on Zenodo) provide free PIDs.
Using PIDs and registering your work with these service providers contributes to greater recognition of your materials.

::: {.callout-tip title="What is a Digital Object Identifier (DOI)?" collapse="true"}

A Digital Object Identifier (DOI) is a unique alphanumeric string assigned to a digital document or resource to provide a permanent and stable link to it.
DOIs are commonly used to identify and provide a persistent link to scholarly articles, research papers, books, datasets, and other types of digital content.
The purpose of a DOI is to ensure that the content can be reliably located and accessed over time, even if the web address (URL) of the resource changes.

Key features of DOIs include:

1. **Uniqueness:** Each DOI is unique to a particular resource, ensuring that no two resources have the same identifier.

2. **Persistence:** DOIs are designed to remain unchanged, providing a persistent link to the resource even if it is moved or the URL changes.

3. **Interoperability:** DOIs are widely used in scholarly publishing and other sectors, making them interoperable across different systems and platforms.

4. **Accessibility:** DOIs are often associated with metadata that provides information about the resource, such as author, title, publisher, publication date, and more.

5. **Citations:** DOIs are commonly used in academic and scientific citations to provide a standardized and reliable reference to a specific resource.

DOIs are typically assigned and managed by registration agencies, such as CrossRef for scholarly content or DataCite for research data. Organizations and publishers assign DOIs to their digital content to enhance discoverability, citation tracking, and long-term accessibility.

:::

::: {.callout-note collapse="true"}
## How does Zenodo work?
To find out how to get a DOI on Zenodo, read the chapter on Zenodo.
:::

::: {.callout-caution collapse="true"}
## How do you protect your material from link rot? {.unnumbered}
- [ ] I have registered my materials on Zenodo and obtained a DOI.
- [ ] I share my work via ORCID.
:::

## Rule 4: Register your training materials online {.unnumbered}
To make the materials even more findable, online registration offers a valuable opportunity.
A general platform for online registration is the [Open Educational Resources Initiative](https://asccc-oeri.org/).
Based on the audience of the materials, there are online platforms that host specific materials.
"Online registration can also be done via tools like TeSS (Training eSupport System), which is focused on life sciences.
In psychology, it is possible to register your work with the Society for the Teaching of Psychology [STP]({{< var links.STP >}}).

::: {.callout-caution collapse="true"}
## Do you register your work online? {.unnumbered}
- [ ] I have registered my materials on OERI, TeSS, STP or similar platforms.
:::


## Rule 5: Define access rules for your training materials {.unnumbered}
Although we promote the openness of teaching materials, there may be situations in which one may not want to share the materials openly.
For example, the materials may be crafted specifically for a particular institution, or access is restricted to certain members of a university.
In these cases, it is important to clearly state the access levels and how one can request access to the materials.
This description should contain information about whether the materials are free or paid, and whether there is a way to authenticate access to the materials.
It is also necessary to clarify accessibility in the metadata, even if the materials are openly accessible to everyone and shared on the web.

::: {.callout-caution collapse="true"}
## How do you deal with the access rules for your materials? {.unnumbered}
- [ ] I clearly state the access level on the dedicated website for the materials.
- [ ] My materials require a specific membership, so I have set up authentication steps for the members.
- [ ] My materials are free and open access, but I have still described the accessibility level in their metadata.
:::


## Rule 6: Use an interoperable format for your training materials {.unnumbered}

FAIR principles try to guarantee the interoperability of the materials.
Most university lectures and seminars are accompanied by a series of slides, scripts, research papers and other types of digital content.
Interoperibality makes sure that one piece of content can be used and developed in another context than its original one.
For instance, slides are mostly developed with Microsoft PowerPoint.
However, PowerPoint documents are limited to Windows and MacOS users, are susceptible to incompatibility with older versions of the software, need the same fonts on all the computers to run properly, are not open-source, and can't be easily used for collaboration and version control.
There are other formats such as PDF, Keynote, online versions of Microsoft Office that more or less have the same problems as PowerPoint documents.
To remedy the aforementioned issues, one can use the LaTeX typesetting system or markdown tools.
LaTeX, RMarkdown, and more recently Quarto are the tools that show how choosing the correct text formatting system contributes to the FAIRness of the materials.
However, we should not forget that these formats have their own weaknesses such as having a relatively steep learning curve and being the most effective when online, which may be limiting.

::: {.callout-note collapse="true"}
### PowerPoint, PDF, TeX, or Markdown?

Here is a detailed comparison between different tools used to create and present educational content by @garcia2020

| **Format**             | **Advantages**                                                                  | **Disadvantages**                                                                                                                     |
|------------------------|---------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|
| **PPT and PPTX**       | • Easily (re)usable<br>• Available to multiple OSs/Software<br>• Widespread<br> | • Limited way to provide detailed training instructions<br>• Not version controlled<br>                                               |
| **Keynote**            | • Polished overall aesthetic                                                    | • Limited to macOS family<br>• Not version controlled<br>                                                                             |
| **PDF**                | • Can be displayed identically in any environment                               | • Not easily editable<br>• Not version controlled                                                                                     |
| **TeX**                | • Easily editable<br>• Version controlled<br>• Free                             | • Steep learning curve for trainers                                                                                                   |
| **MD, RST, and, HTML** | • Version controlled <br>• Free                                                 | • Rendering (need templating to transform into HTML)<br>                                                                              |
| **Google slides**      | • Version controlled<br>• Free                                                  | • Not always possible to use owing to local/ institutional policies<br>• Not always accessible (depending on geographic location)<br> |


*MD, Markdown; PDF, Portable Document Format; PPT, PowerPoint; PPTX, PowerPoint Open XML Presentation;
RST, reStructuredText*

:::

::: {.callout-caution collapse="true"}
## How do you make your material more interoperable? {.unnumbered}
- [ ] I use version controlled Markdown tools.
- [ ] My materials can be (re)used across multiple operating systems.
- [ ] I enhance the materials' interoperability by including instructions.
:::

## Rule 7: Make it (RE)Useable for the Trainers {.unnumbered}
Choosing the appropriate tool to develop the materials is important, but what if we make it even easier for others to (re)use our content?
Licensing is a broad topic covered in **CAHPTER ON LICENSES**.
In short, licenses let others know to what extent they are allowed to (re)use, modify, take inspiration from your work.
Universities and other institutions may have their own regulations for the materials developed by their affiliates.
This may limit the reach of your materials but stating and adhering to the regulations is necessary.
The most used license for free and open access materials is the Creative Commons (CC) license.
It grants rights to others to (re)use the materials.
Licensing is also important for getting recognition for your work and the way it should be cited.

::: {.callout-caution collapse="true"}
## How do you make your materials (re)usable?
- [ ] I have chosen the correct license and stated that in the metadata.
- [ ] I stated how my material should be cited.
- [ ] I have reviewed my institution's regulations regarding licensing materials.
:::

## Rule 8: Don't Forget the Trainees {.unnumbered}
When developing the materials we always have the audience in mind.
After all, the material is going to help the trainees with learning a new skill and transfer knowledge.
Below is a list of metadata, suggested by @garcia2020 that orients the trainees before, while, and after dealing with the materials.

| **Type of metadata**              | **What to include**                                                                                                                                       |
|-----------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Title**                         | Title of the training material.                                                                                                                           |
| **Contact details**               | Author(s) name and contact details.                                                                                                                       |
| **Licensing and (re)use details** | License under which the materials are shared, and rules and conditions for (re)use and<br>contribution.<br>                                               |
| **Preferred citation**            | Instructions on how to cite your material.<br>                                                                                                            |
| **Description **                  | Overview of the subject matter, aims of the training, and language in which the training is delivered.                                                    |
| **Learning outcomes**             | Statements that indicate what trainees should be able to do upon successful completion of the training.                                                   |
| **Target audience**               | The intended audience, their prerequisite knowledge and skills, their general background, and how the training material will help them.                   |
| **Required resources**            | Technical resources and related materials (software requirements, datasets, infrastructure requirements, etc.).                                           |
| **Keyword **                      | Keywords or tags identifying the topic of the materials.                                                                                                  |
| **Structure and duration**        | Description of the structure of the materials and setting in which to deliver them, including the time allocated to each part (lectures, exercises, etc.) |
| **Additional information**        | Items that provide additional information about (re)use and delivery of the materials (e.g., general tips and guidance).                                  |
| **Links and references**          | Links and references that are relevant to the content but not required for delivery of the materials.                                                     |
| **Date of last revision**         | Date of last update of the materials and the version.                                                                                                     |

## Rule 9: Make it Contribution Firendly {.unnumbered}
Contribution is a means of improving the materials.
Others may offer new perspectives, find issues, suggest recommendations for enhancement, etc.
Using a CONTRIBUTION file, you can guide users on how to contribute to your work and define how they should contribute.
A well-known contribution-friendly environment is GitHub, which provides numerous tools for cooperation.
Also, contribution must be acknowledged.

::: {.callout-caution collapse="true"}
## Is your material contribution friendly?
- [ ] I have created a CONTRIBUTION file.
- [ ] I thank and acknowledge the contributors.
- [ ] I use GitHub or similar platforms to keep my materials contribution-friendly.
:::

## Rule 10: Keep the Materials Up-to-date {.unnumbered}
Depending on the materials, they may need to be updated.
You have to keep track of the changes in your materials over time.
The older versions should be archived, the changes should be stated, and if needed the PIDs should be updated as well.
Following the previous rules makes it extremely easy to keep your materials up-to-date.
Also, tools like Quarto and Git make it easy to update the materials and share them across different platforms.

::: {.callout-caution collapse="true"}
## How do you update your materials?
- [ ] I archive the older versions.
- [ ] I clearly document the changes made in each updated version.
- [ ] I keep the PIDs updated.
- [ ] I organize my materials in a way to make the updating process as easy as possible.
:::

## What is Missing from FAIR Principles? {.unnumbered}
FAIR principles emphasize the importance of registering, sharing, and describing materials.
These values also offer clear steps on how to implement them.
The part which seems to be missing is the collaboration.
Although interoperability and reusability are the closer concepts to collaboration, they don't provide enough information on the actual collaboration process in research.
These principles seem passive, meaning they put emphasis on the research data which have been produced and now researchers want to (re)use or reproduce them.
The process of research and also developing teaching materials is a dynamic procedure.
This can't be completely achieved by only adhering to the FAIR principles.
In this guide, we also encourage collaborative work, not only in our words, but also through action.
We developed this guide within a FAIR and collaborative workflow.

::: {.callout-caution collapse="true"}
## How collaboration-friendly are your materials?
- [ ] I use Git or similar platforms.
- [ ] I provide enough metadata for other collaborators.
:::

## Why Quarto? {.unnumbered}
We rely on two tools that we think are fundamental for making such educational materials, namely Git and Quarto, which can relatively guarantee the FAIRness of the materials, if used properly.
Quarto can create slides, websites, and books with different output formats like HTML, PDF, ePUB, PPTX, etc.
Even PowerPoint slides can be converted into `.qmd` files.
Since Quarto documents are text-based, nearly every computer can open and interact with them, as opposed to PowerPoint documents that might be incompatible with older systems and versions of Microsoft Office.
Version controllability is also another advantage of Quarto over PowerPoint and similar software.
Quarto offers features like variables, YML formatting, code execution in multiple languages, informative syntax errors, and interactivity that are not available in other tools.
As this guide focuses on Quarto, [The Version Control Book](https://lennartwittkuhn.com/version-control-book) by [Lennart Wittkuhn](https://lennartwittkuhn.com) and Konrad Pagenstedt (2024) on Git is recommended reading, as Quarto and Git can be extremely powerful tools when used together.



