---
title: "Introduction to Creating Slides"
abstract: "This chapter outlines the basic steps for creating slides in Quarto."
---

## Slides are More FAIR with Quarto
An important part of teaching is presenting.
PowerPoint presentations are widely used across educational settings.
However, PowerPoint comes with several constraints in terms of FAIRness.
PowerPoint slides can't be version controlled.
As discussed in the previous chapters, the Quarto-Git integration is a powerful feature that enables the version controllability of slides crafted in Quarto.
Other general advantages of Quarto are also applicable to creating slides.

For instance, the reproducibility of PowerPoint slides on other systems is often a problem.
To run smoothly, PowerPoint slides need the fonts used on the original system.
There are also compatibility limitations, as one can't be sure that the versions will run the same on different machines.
If one embeds the fonts, animations, images, etc., in PowerPoint, then the slides can't be edited on other machines.

In this chapter, we show how to create basic slides in Quarto.

## First step
The first step to create slides on Quarto is changing the `format` to `revealjs` in the `yml` header.

```yml

---
title: "My First Presentation on Quarto"
format: revealjs
---

```

## Let's Start!
Using level 2 headings `##`, your first slide is created.

```yml

---
title: "Cognitive Neuroscience Methods"
subtitle: "Applied to Aging Research"
format: revealjs
---

## Reduction in Gray Matter (GM) Volume

- Fontal regions (including prefrontal cortex), striatum and hippocampus seem to be most affected by this age-induced deterioration while the occipital lobe remains the least affected.

- More recently, also found changes  in GM volume in the cerebellum.

## Reduction in White Matter (WM) Integrity

- White matter is the the myelin sheath surrounding neuronal axons.

- Inverted U shape relationship between white matter changes and age.

- May explain some of the age-related changes seen in processing speed.

```


```{=html}
<iframe width="100%" height=500 src="example-slides\CN-Slides.html"></iframe>
```


## Incremental Lists
You can define, wether the contents should appear incrementally on the slide via `yml` header.
All needed is to set `incremental` to `true`.
This makes all the lists appear incrementally on the slides.

```yml
---
title: "Cognitive Neuroscience Methods"
subtitle: "Applied to Aging Research"
format:
  revealjs:
    incremental: true
---
```

If you want to make an exception for a slide, you can add `{.nonincremental}` class to that slide.
Also a `{.incremental}` class can be used when `incremental` is `false` on the `yml` header.


```yml

## Reduction in Gray Matter (GM) Volume

- Fontal regions (including prefrontal cortex), striatum and hippocampus seem to be most affected by this age-induced deterioration while the occipital lobe remains the least affected.

- More recently, also found changes  in GM volume in the cerebellum.

## Reduction in White Matter (WM) Integrity

::: {.nonincremental}
- White matter is the the myelin sheath surrounding neuronal axons.

- Inverted U shape relationship between white matter changes and age.

- May explain some of the age-related changes seen in processing speed.
:::
```
```{=html}
<iframe width="100%" height=500 src="example-slides\incremental-lists.html"></iframe>
```

## Columns
To separate contents in a more organized manner, `{.columns}` are useful.
This allows a side by side presentations of contents.
You can also manage the `width` of each column.

```yml
## Neurotransmitter Changes

:::: {.columns}

::: {.column width="60%"}

- **Dopamine**

- Dopamine levels decline up to 10% per decade from early adulthood.

- Associated with cognitive decline and motor performance.

:::

::: {.column width="40%"}

- **Serotonin**

- Age-related declines per decade of 1.5% - 7% of serotonin receptors in the brain.

- Leads to an increase in [reliance on passive]{.underline} versus active decision strategies (Karrer et al., 2019).

:::

::::

```
```{=html}
<iframe width="100%" height=500 src="example-slides\columns.html"></iframe>
```

## More Content on One Slide!

What if you want to add more about the effects of aging on Serotonin and Dopamine!
There is not much space for anything else in the previous slide, right?
Quarto has two features to overcome this limitation.
First, the intuitive way, is to make the text `{.smaller}`.
Add the {.smaller} in line with the title of the slide.
```yml
## Neurotransmitter Changes {.smaller}

:::: {.columns}

::: {.column width="60%"}

**Dopamine**

- Dopamine levels decline up to 10% per decade from early adulthood.

- Associated with cognitive decline and motor performance.

- Neurodegeneration of dopamine neurons leads to [noisier information processing]{.underline} (less distinctive cortical representations)

- Dopamine modulates [prefrontal processing]{.underline} (leading to difficulties with decision-making and planning)

- Dopamine modulates [hippocampal plasticity and memory]{.underline}

:::

::: {.column width="40%"}

**Serotonin**

- Age-related declines per decade of 1.5% - 7% of serotonin receptors in the brain.

- Leads to an increase in [reliance on passive]{.underline} versus active decision strategies (Karrer et al., 2019).

- [Stronger]{.underline} responses to aversive outcomes 

- [Pervasive]{.underline} responding

:::

::::
```

```{=html}
<iframe width="100%" height=500 src="example-slides\smaller.html"></iframe>
```

The second option is to make the slides `{.scrollable}` to scroll through the slide and cover all the matrials.
This option can also be applied usin the `yml` header.
```yml
## Neurotransmitter Changes {.scrollable}

:::: {.columns}

::: {.column width="60%"}

**Dopamine**

- Dopamine levels decline up to 10% per decade from early adulthood.

- Associated with cognitive decline and motor performance.

- Neurodegeneration of dopamine neurons leads to [noisier information processing]{.underline} (less distinctive cortical representations)

- Dopamine modulates [prefrontal processing]{.underline} (leading to difficulties with decision-making and planning)

- Dopamine modulates [hippocampal plasticity and memory]{.underline}

:::

::: {.column width="40%"}

**Serotonin**

- Age-related declines per decade of 1.5% - 7% of serotonin receptors in the brain.

- Leads to an increase in [reliance on passive]{.underline} versus active decision strategies (Karrer et al., 2019).

- [Stronger]{.underline} responses to aversive outcomes 

- [Pervasive]{.underline} responding

:::

::::
```

```{=html}
<iframe width="100%" height=500 src="example-slides\scrollable.html"></iframe>
```


## Slide-Script Integration
Scripts can be integrated into the slides as discussed in the "How to show code?" chapter.
This integration is particularly useful for educational purposes, as the result and function of different chunks of a script can be presented in real time.
Slide-script integration encourages researchers to publish in a more reproducible manner.
Imagine you are presenting a paper's findings, and instead of adding a screenshot of the diagrams, you use the actual script that the authors used to produce that specific output.
Not only would the presentation be cleaner, but also, by doing what you preach, the audience to whom the slides are presented will be in direct contact with how FAIRness impacts the research and educational setting.

```r
library(ggplot2)

# Data preparation
age_groups <- c("under 1 year", "1-5 years", "6-14 years", "15-17 years", 
                "18-20 years", "21-24 years", "25-39 years", "40-59 years", 
                "60-64 years", "65 years and older")
population <- c(0.74, 4.08, 6.32, 3.11, 2.44, 3.69, 16.11, 23, 6.2, 18.66)
data <- data.frame(AgeGroup = age_groups, Population = population)

# Bar chart creation
plot <- ggplot(data, aes(x = AgeGroup, y = Population)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = Population), vjust = -0.5, size = 3.5) +
  labs(
    title = "Population of Germany as of December 31, 2022, by age group (in millions)",
    x = "Age Group",
    y = "Population in millions",
    caption = "Source: Statistisches Bundesamt \u00A9 Statista 2023\nAdditional Information: Germany; Statistisches Bundesamt; December 31, 2022"
  ) +
  scale_y_continuous(breaks = seq(0, 30, 5), limits = c(0, 30)) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

# Display the chart
print(plot)

```

```{=html}
<iframe width="100%" height=500 src="example-slides\script-slide.html"></iframe>
```




## Minor Details

### Footnotes
Same as the text formatting, `^[]` is used to add footnotes to the text.

### Asides
To add asides, Quarto wants you to push the text `aside`!

### Logo and Footer
By changing the `yml` header it is possible to add a footer and a logo to the slides.
Custom footer for each slide is also available.

The script presented below, is an illustration of all the aforementioned minor details.

```yml

---
format:
  revealjs:
    logo: ../../images/uhh.png
    footer: "Cognitive Neuroscience Methods Applied to Aging Research"
---
## Neurotransmitter Changes {.smaller}

:::: {.columns}

::: {.column width="60%"}

**Dopamine**

- Dopamine levels decline up to 10% per decade from early adulthood.

- Associated with cognitive decline and motor performance.

- Neurodegeneration of dopamine neurons leads to [noisier information processing]{.underline} (less distinctive cortical representations)

- Dopamine modulates [prefrontal processing]{.underline} (leading to difficulties with decision-making and planning)

- Dopamine modulates [hippocampal plasticity and memory]{.underline}

:::

::: {.column width="40%"}

**Serotonin**

- Age-related declines per decade of 1.5% - 7% of serotonin receptors in the brain.

- Leads to an increase in [reliance on passive]{.underline} versus active decision strategies ^[(Karrer et al., 2019)].

- [Stronger]{.underline} responses to aversive outcomes 

- [Pervasive]{.underline} responding

:::

::::

::: aside
In the nect session we will talk more about this topic.
:::

```

```{=html}
<iframe width="100%" height=500 src="example-slides\minor-details.html"></iframe>
```


## Add Images to the slides
## Transitions
## Fragments

## Presenting Options

While presenting, you can switch between different presentation modes and take advantage of built-in Quarto presentation features.
The three lines on the bottom left of the slides open the presentation menu bar.
On the menu bar, Slides shows the title of each slide, and you can navigate through the slides.
The `Tools` menu is where things get interesting.
The most useful features on this menu are `Speaker View`, `Slide Overview`, `Toggle Chalkboard`, and `Toggle Notes`.
These options are activated on the example slides in this chapter; therefore, you can discover them in this chapter as well.

#### Speaker View

`Speaker View` is the equivalent of PowerPoint's Presenter View.
Your notes and the upcoming slide are shown.
A timer and a clock also help you keep track of time while presenting.
Pressing `s` acts as a shortcut for this option.

#### Slide Overview

This option, which is activated by pressing `o`, gives an overview of your previous and next slides to navigate through them quickly.

#### Toggle Chalkboard & Toggle Notes Canvas

These features are relatively the same in terms of function.
`Toggle Chalkboard` opens a separate "Chalkboard" window where you can write and draw using different brushes.
Its shortcut is `b` on the keyboard.
By pressing `c` and opening the `Toggle Notes Canvas`, you can write on the slides.
You can download the drawings by pressing `d`.
Make sure to activate these options in your presentation by adding `chalkboard: true` under the `revealjs` section in the `.yml` header of your presentation.

## Acknowledgements
Thanks to *[Dr. Alexa Ruel](https://alexaruel.github.io/)* for letting us use her PowerPoint slides as examples to transform them into Quarto slides.